version: '3.8'
services:
  api:
    container_name: home-cloud-api
    build: ./api
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    container_name: home-cloud-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  